# Generated by Django 5.0.2 on 2024-03-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('India', 'India'), ('Paris', 'Paris'), ('France', 'France'), ('New York', 'New York')], max_length=250)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=1)),
                ('special_request', models.TextField(blank=True)),
            ],
        ),
    ]
